### ISSUE TITLE
Templates have hard-coded OpenStack references

### ISSUE THREAD

**Issue by crazyscientist** [SUSE/suse-sphinx-theme#6]
This is more like a question than an issue:

The templates contain lots of OpenStack branding:

* In the `<title>` tag it says "OpenStack docs"
* In the footer bar there are lots of links very specific for the OpenStack project

In order to use this theme for different projects might it not be nice to be able to *configure* the title prefix and the links in the footer?

**Comment by jeremy-moffitt** [comment]
I think this would be pretty handy, though as with what Adam indicated, our initial use for this is for the upstream OpenStack docs. As long as that use case is served, I'm all for any changes that make it easier for someone else to adopt the doc theme if they want to!

**Comment by crazyscientist** [comment]
Thanks for your feedback. I will make a first short example to see whether you like the way I'm heading for.

**Comment by crazyscientist** [comment]
1. I found the `root_title` option in `theme.conf` that can be overwritten from `conf.py`.
2. Instead of writing code to generate a project-specific footer I simply can put a project-specific `footer.html` in to the templates folder of my project.

I think this is fine enough :smile:
